import fs from 'node:fs'
import path from 'node:path'
import { PLUGIN_NAME, logWarn } from './logger.js'

const GENERATED_MARKER = '# Generated by vitepress-plugin-openspec'

/**
 * Returns how strongly a directory looks like a real openspec/ source folder.
 * - 'strong': unambiguous markers (project.md, config file, spec.md, change yaml)
 * - 'weak': only an archive layout — valid for real sources that contain only
 *   archived changes, but also matches unmarked generated output, so it is
 *   only used when no strong candidate exists anywhere up the tree
 * - false: generated output (identified via its generated .gitignore marker)
 *   or no openspec structure at all
 */
export function looksLikeOpenSpecDir(dir: string): 'strong' | 'weak' | false {
  const gitignore = path.join(dir, '.gitignore')
  if (fs.existsSync(gitignore)) {
    try {
      if (fs.readFileSync(gitignore, 'utf-8').startsWith(GENERATED_MARKER)) return false
    } catch {
      // ignore unreadable files
    }
  }
  if (fs.existsSync(path.join(dir, 'project.md'))) return 'strong'
  if (fs.existsSync(path.join(dir, 'config.yaml')) || fs.existsSync(path.join(dir, 'config.yml'))) return 'strong'
  const changesDir = path.join(dir, 'changes')
  if (fs.existsSync(changesDir)) {
    try {
      for (const entry of fs.readdirSync(changesDir, { withFileTypes: true })) {
        if (!entry.isDirectory() && !entry.name.endsWith('.yaml')) continue
        const marker = path.join(changesDir, entry.name, '.openspec.yaml')
        const yaml = path.join(changesDir, `${entry.name}.yaml`)
        if (fs.existsSync(marker) || fs.existsSync(yaml)) return 'strong'
      }
    } catch {
      // ignore unreadable directories
    }
  }
  const specsDir = path.join(dir, 'specs')
  if (fs.existsSync(specsDir)) {
    try {
      for (const entry of fs.readdirSync(specsDir, { withFileTypes: true })) {
        if (!entry.isDirectory()) continue
        if (fs.existsSync(path.join(specsDir, entry.name, 'spec.md'))) return 'strong'
      }
    } catch {
      // ignore unreadable directories
    }
  }
  const archiveDir = path.join(changesDir, 'archive')
  if (fs.existsSync(archiveDir)) {
    try {
      if (fs.readdirSync(archiveDir, { withFileTypes: true }).some((e) => e.isDirectory())) return 'weak'
    } catch {
      // ignore unreadable directories
    }
  }
  return false
}

/**
 * Walks up from `start` looking for a real `openspec/` folder. The nearest
 * valid source wins: an archive-only (weak) source found on the way up is
 * preferred over any strong source further up the tree, while unmarked
 * generated output at the output location is skipped as interrupted output.
 * This keeps the plugin zero-config: users do not need to pass `specDir` when
 * `openspec/` lives at the project root, even when VitePress is invoked from
 * a subfolder.
 */
export function findOpenSpecDir(start: string, generatedOutputDir?: string): string | undefined {
  let current = path.resolve(start)
  for (;;) {
    const candidate = path.join(current, 'openspec')
    if (fs.existsSync(candidate)) {
      const match = looksLikeOpenSpecDir(candidate)
      // A weak match at the generated output location is unmarked output
      // from an interrupted run — keep searching for the real source.
      if (match === 'weak' && generatedOutputDir && realPath(candidate) === realPath(generatedOutputDir)) {
        const parent = path.dirname(current)
        if (parent === current) return undefined
        current = parent
        continue
      }
      if (match === 'strong' || match === 'weak') return candidate
    }
    const parent = path.dirname(current)
    if (parent === current) return undefined
    current = parent
  }
}

/**
 * Resolves a path to its canonical form, following symlinks of the deepest
 * existing ancestor so containment checks are not defeated by symlinked
 * output directories.
 */
export function realPath(target: string): string {
  let current = path.resolve(target)
  const suffix: string[] = []
  for (;;) {
    if (fs.existsSync(current)) break
    const parent = path.dirname(current)
    if (parent === current) return path.resolve(target)
    suffix.unshift(path.basename(current))
    current = parent
  }
  try {
    current = fs.realpathSync(current)
  } catch {
    return path.resolve(target)
  }
  return suffix.length ? path.join(current, ...suffix) : current
}

const srcDirCache = new Map<string, string | undefined>()

/**
 * Detects the VitePress source directory (the folder containing `.vitepress`)
 * by checking the current working directory and its first-level subdirectories
 * (e.g. `docs/.vitepress`). Falls back to the working directory itself.
 *
 * Cached per working directory so repeated calls (e.g. from both
 * `withOpenSpec` and `generateOpenSpecPages` during one config load) do not
 * re-run detection or repeat ambiguity warnings.
 */
export function detectSrcDir(cwd: string): string | undefined {
  const key = path.resolve(cwd)
  if (srcDirCache.has(key)) return srcDirCache.get(key)
  const result = resolveSrcDir(key)
  srcDirCache.set(key, result)
  return result
}

function resolveSrcDir(cwd: string): string | undefined {
  if (path.basename(cwd) === '.vitepress') return path.dirname(cwd)
  if (fs.existsSync(path.join(cwd, '.vitepress'))) return cwd
  const matches: string[] = []
  try {
    for (const entry of fs.readdirSync(cwd, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue
      const subDir = path.join(cwd, entry.name)
      if (fs.existsSync(path.join(subDir, '.vitepress'))) matches.push(subDir)
    }
  } catch {
    // ignore unreadable directories
  }
  if (matches.length === 1) return matches[0]
  if (matches.length > 1) {
    const docsMatch = matches.find((m) => path.basename(m) === 'docs')
    if (docsMatch) return docsMatch
    logWarn(
      `Multiple VitePress source directories found (${matches
        .map((m) => path.relative(cwd, m))
        .join(', ')}) — pass an explicit \`srcDir\` option. Skipping page generation.`,
    )
    return undefined
  }
  return cwd
}

/**
 * Detects the VitePress project root — the directory containing the
 * `.vitepress` folder — so a relative `srcDir` from the wrapped config can be
 * resolved the same way VitePress resolves it.
 */
export function detectVitePressRoot(cwd: string): string {
  const srcDir = detectSrcDir(cwd)
  return srcDir && fs.existsSync(path.join(srcDir, '.vitepress')) ? srcDir : cwd
}
