import fs from 'node:fs'
import path from 'node:path'
import type { Change } from '../types.js'
import type { ResolvedOptions } from './options.js'
import { logError, logInfo, logWarn } from './logger.js'
import { readOpenSpecFolder } from './reader.js'
import { rewriteRelativeLinks } from './links.js'
import {
  generateChangeIndexPage,
  generateChangesIndexPage,
  generateRootIndexPage,
  generateSpecPage,
  generateSpecsIndexPage,
} from './pages.js'

const MANIFEST_FILE = '.openspec-manifest.json'
const GITIGNORE_CONTENT = '# Generated by vitepress-plugin-openspec — do not commit generated files.\n*\n!.gitignore\n'

function writeFile(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, 'utf-8')
}

function pruneEmptyDirs(rootDir: string, startDir: string): void {
  let dir = startDir
  while (dir.startsWith(rootDir) && dir !== rootDir) {
    try {
      if (fs.readdirSync(dir).length > 0) break
      fs.rmdirSync(dir)
    } catch {
      break
    }
    dir = path.dirname(dir)
  }
}

/**
 * Reads the previous run's manifest and deletes all recorded files.
 * Runs BEFORE the new pages are written so that case-only renames on
 * case-insensitive filesystems cannot make stale cleanup delete a
 * freshly generated page that shares the same file.
 *
 * @returns entries whose deletion failed; they are retained in the next
 * manifest so cleanup retries instead of forgetting them.
 */
function cleanupPreviousManifest(rootDir: string): string[] {
  const manifestPath = path.join(rootDir, MANIFEST_FILE)
  if (!fs.existsSync(manifestPath)) return []
  let previous: string[] = []
  try {
    const parsed = JSON.parse(fs.readFileSync(manifestPath, 'utf-8')) as unknown
    if (Array.isArray(parsed)) previous = parsed.filter((f): f is string => typeof f === 'string')
  } catch {
    // Unreadable manifest: treat as empty
    return []
  }
  const retained: string[] = []
  for (const entry of previous) {
    const entryPath = path.resolve(rootDir, entry)
    const rel = path.relative(rootDir, entryPath)
    if (rel.startsWith('..') || path.isAbsolute(rel)) continue
    try {
      if (fs.existsSync(entryPath)) {
        fs.rmSync(entryPath)
        pruneEmptyDirs(rootDir, path.dirname(entryPath))
      }
    } catch {
      // Deletion failed (e.g. locked file): retry on the next run
      retained.push(entry)
    }
  }
  return retained
}

function writeManifest(files: string[], rootDir: string): void {
  const manifestPath = path.join(rootDir, MANIFEST_FILE)
  try {
    writeFile(manifestPath, JSON.stringify(files, null, 2))
  } catch {
    // Best-effort: never fail generation because of the manifest
  }
}

function writeChangePage(
  change: Change,
  options: ResolvedOptions,
  isArchived: boolean,
): string[] {
  const subPath = isArchived
    ? path.join('changes', 'archive', change.archiveFolderName ?? change.name)
    : path.join('changes', change.name)
  const changeOutDir = path.join(options.absoluteOutDir, subPath)
  const written: string[] = []

  const indexPath = path.join(changeOutDir, 'index.md')
  writeFile(indexPath, generateChangeIndexPage(change, options.outDir))
  written.push(path.relative(options.absoluteOutDir, indexPath))

  for (const artifact of change.artifacts) {
    const srcFile = path.join(change.dir, `${artifact}.md`)
    const destFile = path.join(changeOutDir, `${artifact}.md`)
    // When specDir and outDir overlap, never copy a file onto itself
    if (path.resolve(srcFile) === path.resolve(destFile)) continue
    const content = fs.readFileSync(srcFile, 'utf-8')
    writeFile(destFile, rewriteRelativeLinks(content, srcFile, options.specDir, options.outDir))
    written.push(path.relative(options.absoluteOutDir, destFile))
  }
  return written
}

/**
 * Synchronously generates all VitePress Markdown pages from the openspec/
 * directory and writes them to disk, removing stale output from previous runs.
 */
export function generatePages(options: ResolvedOptions): void {
  // Remove stale output from the previous run even when the source
  // directory has disappeared, so published pages do not linger forever.
  const retained = cleanupPreviousManifest(options.absoluteOutDir)

  if (!fs.existsSync(options.specDir)) {
    logWarn(
      `openspec directory not found: ${path.relative(options.srcDir, options.specDir)} — skipping page generation`,
    )
    // Persist only what still needs a retry; do not create an output
    // directory when there is nothing to clean up or retain.
    if (retained.length > 0 || fs.existsSync(options.absoluteOutDir)) {
      writeManifest(retained, options.absoluteOutDir)
    }
    return
  }

  try {
    const folder = readOpenSpecFolder(options.specDir)
    const written: string[] = []

    for (const spec of folder.specs) {
      const dest = path.join(options.absoluteOutDir, 'specs', spec.name, 'index.md')
      writeFile(dest, generateSpecPage(spec))
      written.push(path.relative(options.absoluteOutDir, dest))
    }

    const specsIndexPath = path.join(options.absoluteOutDir, 'specs', 'index.md')
    writeFile(specsIndexPath, generateSpecsIndexPage(folder.specs, options.outDir))
    written.push('specs/index.md')

    for (const change of folder.changes) {
      written.push(...writeChangePage(change, options, false))
    }
    for (const change of folder.archivedChanges) {
      written.push(...writeChangePage(change, options, true))
    }

    const changesIndexPath = path.join(options.absoluteOutDir, 'changes', 'index.md')
    writeFile(changesIndexPath, generateChangesIndexPage(folder, options.outDir))
    written.push('changes/index.md')

    const rootIndexPath = path.join(options.absoluteOutDir, 'index.md')
    writeFile(rootIndexPath, generateRootIndexPage(options.outDir))
    written.push('index.md')

    writeFile(path.join(options.absoluteOutDir, '.gitignore'), GITIGNORE_CONTENT)

    writeManifest([...written, ...retained], options.absoluteOutDir)

    logInfo(
      `Generated docs from ${options.specDir}: ` +
        `${folder.specs.length} spec(s), ${folder.changes.length} change(s), ` +
        `${folder.archivedChanges.length} archived`,
    )
  } catch (err) {
    logError(`Failed to process openspec directory "${options.specDir}": ${String(err)}`)
  }
}
