import fs from 'node:fs'
import path from 'node:path'
import { invalidateGeneratedDestinations } from './watch.js'
import type { Change } from '../types.js'
import type { ResolvedOptions } from './options.js'
import { logError, logInfo, logWarn } from './logger.js'
import { readOpenSpecFolder } from './reader.js'
import { rewriteRelativeLinks } from './links.js'
import {
  generateChangeIndexPage,
  generateChangesIndexPage,
  generateRootIndexPage,
  generateSpecPage,
  generateSpecsIndexPage,
} from './pages.js'

export const MANIFEST_FILE = '.openspec-manifest.json'
const GITIGNORE_CONTENT = '# Generated by vitepress-plugin-openspec — do not commit generated files.\n*\n!.gitignore\n'

interface OutputFile {
  /** Path relative to absoluteOutDir, using forward slashes */
  rel: string
  content: string
}

function writeFile(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, 'utf-8')
}

function toRel(absoluteOutDir: string, filePath: string): string {
  return path.relative(absoluteOutDir, filePath).split(path.sep).join('/')
}

function pruneEmptyDirs(rootDir: string, startDir: string): void {
  let dir = startDir
  while (dir.startsWith(rootDir) && dir !== rootDir) {
    try {
      if (fs.readdirSync(dir).length > 0) break
      fs.rmdirSync(dir)
    } catch {
      break
    }
    dir = path.dirname(dir)
  }
}

/**
 * Reads the previous run's manifest and deletes all recorded files.
 * Runs only after the replacement generation has been fully read and
 * rendered in memory, so a failing source read never destroys the last
 * successful output. Because cleanup precedes writing the new files, a
 * stale entry can never resolve to a freshly written page, even for
 * case-only renames on case-insensitive filesystems.
 *
 * @returns entries whose deletion failed; they are retained in the next
 * manifest so cleanup retries instead of forgetting them.
 */
function cleanupPreviousManifest(rootDir: string): string[] {
  const manifestPath = path.join(rootDir, MANIFEST_FILE)
  if (!fs.existsSync(manifestPath)) return []
  let previous: string[] = []
  try {
    const parsed = JSON.parse(fs.readFileSync(manifestPath, 'utf-8')) as unknown
    if (Array.isArray(parsed)) previous = parsed.filter((f): f is string => typeof f === 'string')
  } catch {
    // Unreadable manifest: treat as empty
    return []
  }
  const retained: string[] = []
  for (const entry of previous) {
    const entryPath = path.resolve(rootDir, entry)
    const rel = path.relative(rootDir, entryPath)
    if (rel.startsWith('..') || path.isAbsolute(rel)) continue
    try {
      if (fs.existsSync(entryPath)) {
        fs.rmSync(entryPath)
        pruneEmptyDirs(rootDir, path.dirname(entryPath))
      }
    } catch {
      // Deletion failed (e.g. locked file): retry on the next run
      retained.push(entry)
    }
  }
  return retained
}

export function readManifest(rootDir: string): string[] {
  try {
    const parsed = JSON.parse(fs.readFileSync(path.join(rootDir, MANIFEST_FILE), 'utf-8')) as unknown
    if (Array.isArray(parsed)) return parsed.filter((f): f is string => typeof f === 'string')
  } catch {
    // Unreadable or missing manifest: treat as empty
  }
  return []
}

function writeManifest(files: string[], rootDir: string): void {
  const manifestPath = path.join(rootDir, MANIFEST_FILE)
  try {
    writeFile(manifestPath, JSON.stringify(files, null, 2))
    invalidateGeneratedDestinations(rootDir)
  } catch {
    // Best-effort: never fail generation because of the manifest
  }
}

function renderChangePages(
  change: Change,
  options: ResolvedOptions,
  isArchived: boolean,
): OutputFile[] {
  const subPath = isArchived
    ? path.join('changes', 'archive', change.archiveFolderName ?? change.name)
    : path.join('changes', change.name)
  const changeOutDir = path.join(options.absoluteOutDir, subPath)
  const files: OutputFile[] = []

  files.push({
    rel: toRel(options.absoluteOutDir, path.join(changeOutDir, 'index.md')),
    content: generateChangeIndexPage(change, options.outDir),
  })

  for (const artifact of change.artifacts) {
    const srcFile = path.join(change.dir, `${artifact}.md`)
    const destFile = path.join(changeOutDir, `${artifact}.md`)
    // When specDir and outDir overlap, never copy a file onto itself
    if (path.resolve(srcFile) === path.resolve(destFile)) continue
    const content = fs.readFileSync(srcFile, 'utf-8')
    files.push({
      rel: toRel(options.absoluteOutDir, destFile),
      content: rewriteRelativeLinks(content, srcFile, options.specDir, options.outDir),
    })
  }
  return files
}

/**
 * Reads the openspec directory and renders every output page into memory.
 * All source file access happens here, before any destructive step, so
 * an inconsistent source tree cannot destroy the previous output.
 */
function renderAllPages(options: ResolvedOptions): OutputFile[] {
  const folder = readOpenSpecFolder(options.specDir)
  const files: OutputFile[] = []

  for (const spec of folder.specs) {
    const dest = path.join(options.absoluteOutDir, 'specs', spec.name, 'index.md')
    files.push({ rel: toRel(options.absoluteOutDir, dest), content: generateSpecPage(spec) })
  }
  files.push({
    rel: 'specs/index.md',
    content: generateSpecsIndexPage(folder.specs, options.outDir),
  })

  for (const change of folder.changes) {
    files.push(...renderChangePages(change, options, false))
  }
  for (const change of folder.archivedChanges) {
    files.push(...renderChangePages(change, options, true))
  }

  files.push({
    rel: 'changes/index.md',
    content: generateChangesIndexPage(folder, options.outDir),
  })
  files.push({
    rel: 'index.md',
    content: generateRootIndexPage(options.outDir),
  })

  return files
}

/**
 * Synchronously generates all VitePress Markdown pages from the openspec/
 * directory and writes them to disk, removing stale output from previous runs.
 */
export function generatePages(options: ResolvedOptions): void {
  // Remove stale output from the previous run even when the source
  // directory has disappeared, so published pages do not linger forever.
  if (!fs.existsSync(options.specDir)) {
    logWarn(
      `openspec directory not found: ${path.relative(options.srcDir, options.specDir)} — skipping page generation`,
    )
    const retained = cleanupPreviousManifest(options.absoluteOutDir)
    if (retained.length > 0 || fs.existsSync(options.absoluteOutDir)) {
      writeManifest(retained, options.absoluteOutDir)
    }
    return
  }

  // Phase 1: read sources and render everything in memory. A failure here
  // leaves the last successful output untouched.
  let files: OutputFile[]
  try {
    files = renderAllPages(options)
  } catch (err) {
    logError(`Failed to process openspec directory "${options.specDir}": ${String(err)}`)
    return
  }

  // Phase 2: destructive cleanup of the previous output, now that the
  // replacement generation is complete and safe to write.
  const retained = cleanupPreviousManifest(options.absoluteOutDir)

  // Phase 3: write the new pages.
  try {
    for (const file of files) {
      writeFile(path.join(options.absoluteOutDir, file.rel), file.content)
    }
    writeFile(path.join(options.absoluteOutDir, '.gitignore'), GITIGNORE_CONTENT)
    writeManifest([...files.map((f) => f.rel), ...retained], options.absoluteOutDir)
  } catch (err) {
    logError(`Failed to write openspec pages: ${String(err)}`)
    return
  }

  logInfo(`Generated docs from ${options.specDir}: ${files.length} file(s)`)
}
