import fs from 'node:fs'
import path from 'node:path'
import type { Change } from '../types.js'
import type { ResolvedOptions } from './options.js'
import { PLUGIN_NAME, logError, logInfo, logWarn } from './logger.js'
import { readOpenSpecFolder } from './reader.js'
import { rewriteRelativeLinks } from './links.js'
import {
  generateChangeIndexPage,
  generateChangesIndexPage,
  generateRootIndexPage,
  generateSpecPage,
  generateSpecsIndexPage,
} from './pages.js'

const MANIFEST_FILE = '.openspec-manifest.json'
const GITIGNORE_CONTENT = '# Generated by vitepress-plugin-openspec — do not commit generated files.\n*\n!.gitignore\n'

function writeFile(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, 'utf-8')
}

function pruneEmptyDirs(rootDir: string, startDir: string): void {
  let dir = startDir
  while (dir.startsWith(rootDir) && dir !== rootDir) {
    try {
      if (fs.readdirSync(dir).length > 0) break
      fs.rmdirSync(dir)
    } catch {
      break
    }
    dir = path.dirname(dir)
  }
}

function recordManifest(files: string[], rootDir: string): void {
  const manifestPath = path.join(rootDir, MANIFEST_FILE)
  let previous: string[] = []
  if (fs.existsSync(manifestPath)) {
    try {
      const parsed = JSON.parse(fs.readFileSync(manifestPath, 'utf-8')) as unknown
      if (Array.isArray(parsed)) previous = parsed.filter((f): f is string => typeof f === 'string')
    } catch {
      // Unreadable manifest: treat as empty and overwrite it below
    }
  }
  const retained: string[] = []
  for (const stale of previous) {
    if (files.includes(stale)) continue
    const stalePath = path.resolve(rootDir, stale)
    const rel = path.relative(rootDir, stalePath)
    if (rel.startsWith('..') || path.isAbsolute(rel)) continue
    try {
      if (fs.existsSync(stalePath)) {
        fs.rmSync(stalePath)
        pruneEmptyDirs(rootDir, path.dirname(stalePath))
      }
    } catch {
      // Deletion failed (e.g. locked file): keep the entry so the next
      // run retries it instead of forgetting the stale page forever.
      retained.push(stale)
    }
  }
  writeFile(manifestPath, JSON.stringify([...files, ...retained], null, 2))
}

function writeChangePage(
  change: Change,
  options: ResolvedOptions,
  isArchived: boolean,
): string[] {
  const subPath = isArchived
    ? path.join('changes', 'archive', change.archiveFolderName ?? change.name)
    : path.join('changes', change.name)
  const changeOutDir = path.join(options.absoluteOutDir, subPath)
  const written: string[] = []

  const indexPath = path.join(changeOutDir, 'index.md')
  writeFile(indexPath, generateChangeIndexPage(change, options.outDir))
  written.push(path.relative(options.absoluteOutDir, indexPath))

  for (const artifact of change.artifacts) {
    const srcFile = path.join(change.dir, `${artifact}.md`)
    const destFile = path.join(changeOutDir, `${artifact}.md`)
    // When specDir and outDir overlap, never copy a file onto itself
    if (path.resolve(srcFile) === path.resolve(destFile)) continue
    const content = fs.readFileSync(srcFile, 'utf-8')
    writeFile(destFile, rewriteRelativeLinks(content, srcFile, options.specDir, options.outDir))
    written.push(path.relative(options.absoluteOutDir, destFile))
  }
  return written
}

/**
 * Synchronously generates all VitePress Markdown pages from the openspec/
 * directory and writes them to disk, removing stale output from previous runs.
 */
export function generatePages(options: ResolvedOptions): void {
  if (!fs.existsSync(options.specDir)) {
    logWarn(
      `openspec directory not found: ${path.relative(options.srcDir, options.specDir)} — skipping page generation`,
    )
    return
  }

  try {
    const folder = readOpenSpecFolder(options.specDir)
    const written: string[] = []

    for (const spec of folder.specs) {
      const dest = path.join(options.absoluteOutDir, 'specs', spec.name, 'index.md')
      writeFile(dest, generateSpecPage(spec))
      written.push(path.relative(options.absoluteOutDir, dest))
    }

    const specsIndexPath = path.join(options.absoluteOutDir, 'specs', 'index.md')
    writeFile(specsIndexPath, generateSpecsIndexPage(folder.specs, options.outDir))
    written.push('specs/index.md')

    for (const change of folder.changes) {
      written.push(...writeChangePage(change, options, false))
    }
    for (const change of folder.archivedChanges) {
      written.push(...writeChangePage(change, options, true))
    }

    const changesIndexPath = path.join(options.absoluteOutDir, 'changes', 'index.md')
    writeFile(changesIndexPath, generateChangesIndexPage(folder, options.outDir))
    written.push('changes/index.md')

    const rootIndexPath = path.join(options.absoluteOutDir, 'index.md')
    writeFile(rootIndexPath, generateRootIndexPage(options.outDir))
    written.push('index.md')

    writeFile(path.join(options.absoluteOutDir, '.gitignore'), GITIGNORE_CONTENT)

    recordManifest(written, options.absoluteOutDir)

    logInfo(
      `Generated docs from ${options.specDir}: ` +
        `${folder.specs.length} spec(s), ${folder.changes.length} change(s), ` +
        `${folder.archivedChanges.length} archived`,
    )
  } catch (err) {
    logError(`Failed to process openspec directory "${options.specDir}": ${String(err)}`)
  }
}
