import fs from 'node:fs'
import path from 'node:path'
import pc from 'picocolors'
import type { Plugin } from 'vite'
import type { Change, OpenSpecPluginOptions, WithOpenSpecOptions } from './types.js'
import {
  generateChangeIndexPage,
  generateChangesIndexPage,
  generateOpenSpecSidebar,
  generateSpecPage,
  generateSpecsIndexPage,
  openspecNav,
  readOpenSpecFolder,
} from './utils.js'

const PLUGIN_NAME = 'vitepress-plugin-openspec'

function writeFile(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, 'utf-8')
}

function copyFile(src: string, dest: string): void {
  fs.mkdirSync(path.dirname(dest), { recursive: true })
  fs.copyFileSync(src, dest)
}

/**
 * Synchronously generates all VitePress Markdown pages from the openspec/
 * directory and writes them to disk.
 *
 * Call this at the top of your `docs/.vitepress/config.ts` **before**
 * `defineConfig()` so the files exist when VitePress scans the source
 * directory for routes.
 *
 * @example
 * ```typescript
 * // docs/.vitepress/config.ts
 * import { defineConfig } from 'vitepress'
 * import path from 'node:path'
 * import { fileURLToPath } from 'node:url'
 * import openspec, { generateOpenSpecPages } from 'vitepress-plugin-openspec'
 *
 * const __dirname = path.dirname(fileURLToPath(import.meta.url))
 * const specDir = path.resolve(__dirname, '../../openspec')
 *
 * // Generate pages before VitePress scans srcDir for routes
 * generateOpenSpecPages({ specDir, outDir: 'openspec', srcDir: path.resolve(__dirname, '..') })
 *
 * export default defineConfig({ ... })
 * ```
 */
export function generateOpenSpecPages(userOptions: OpenSpecPluginOptions = {}): void {
  const specDir = userOptions.specDir ?? './openspec'
  const outDir = userOptions.outDir ?? 'openspec'
  const srcDir = userOptions.srcDir ?? process.cwd()
  const absoluteOutDir = path.resolve(srcDir, outDir)

  try {
    const folder = readOpenSpecFolder(specDir)

    // --- Spec pages ---
    for (const spec of folder.specs) {
      const dest = path.join(absoluteOutDir, 'specs', spec.name, 'index.md')
      writeFile(dest, generateSpecPage(spec))
    }
    writeFile(
      path.join(absoluteOutDir, 'specs', 'index.md'),
      generateSpecsIndexPage(folder.specs, outDir),
    )

    // --- Active change pages ---
    for (const change of folder.changes) {
      writeChangePage(change, absoluteOutDir, outDir, false)
    }

    // --- Archived change pages ---
    for (const change of folder.archivedChanges) {
      writeChangePage(change, absoluteOutDir, outDir, true)
    }

    // --- Changes index ---
    writeFile(
      path.join(absoluteOutDir, 'changes', 'index.md'),
      generateChangesIndexPage(folder, outDir),
    )

    // --- Root index ---
    const rootIndex = [
      '# Project Documentation',
      '',
      "This section is generated from the project's [OpenSpec](https://openspec.dev/) folder.",
      'OpenSpec is a lightweight, file-based workflow for spec-driven development —',
      'it structures your project\'s capability specifications and change proposals as plain Markdown files.',
      '',
      `- [Specifications](/${outDir}/specs/) — canonical capability specs`,
      `- [Changes](/${outDir}/changes/) — active and archived change proposals`,
      '',
    ].join('\n')
    writeFile(path.join(absoluteOutDir, 'index.md'), rootIndex)

    // Write a self-managed .gitignore so consumers don't need to add the
    // output directory to their project-level .gitignore manually.
    writeFile(
      path.join(absoluteOutDir, '.gitignore'),
      '# Generated by vitepress-plugin-openspec — do not commit generated files.\n*\n!.gitignore\n',
    )

    console.log(
      `${pc.bold(pc.cyan(`[${PLUGIN_NAME}]`))} Generated docs from ${pc.cyan(specDir)}: ` +
        `${pc.green(String(folder.specs.length))} spec(s), ` +
        `${pc.green(String(folder.changes.length))} change(s), ` +
        `${pc.green(String(folder.archivedChanges.length))} archived`,
    )
  } catch (err) {
    console.error(
      `${pc.bold(pc.red(`[${PLUGIN_NAME}]`))} Failed to process openspec directory "${specDir}": ${String(err)}`,
    )
  }
}

/**
 * VitePress plugin that reads an openspec/ directory and generates structured
 * Markdown documentation pages inside the VitePress source directory.
 *
 * For the pages to be available on the first build (including CI), also call
 * `generateOpenSpecPages()` at the top of your `config.ts` before `defineConfig`.
 *
 * @example
 * ```typescript
 * // .vitepress/config.ts
 * import { defineConfig } from 'vitepress'
 * import openspec, { generateOpenSpecPages } from 'vitepress-plugin-openspec'
 *
 * generateOpenSpecPages({ specDir, outDir: 'openspec', srcDir: path.resolve(__dirname, '..') })
 *
 * export default defineConfig({
 *   vite: { plugins: [openspec({ specDir: './openspec', outDir: 'project-docs' })] },
 * })
 * ```
 */
export function openspec(userOptions: OpenSpecPluginOptions = {}): Plugin {
  return {
    name: PLUGIN_NAME,
    enforce: 'pre',

    configResolved(resolvedConfig) {
      const vpConfig = (resolvedConfig as unknown as { vitepress?: { srcDir?: string } }).vitepress
      const srcDir =
        userOptions.srcDir ?? vpConfig?.srcDir ?? resolvedConfig.root ?? process.cwd()
      generateOpenSpecPages({ ...userOptions, srcDir })
    },
  }
}

function writeChangePage(
  change: Change,
  absoluteOutDir: string,
  outDir: string,
  isArchived: boolean,
): void {
  const subPath = isArchived
    ? path.join('changes', 'archive', `${change.archivedDate}-${change.name}`)
    : path.join('changes', change.name)
  const changeOutDir = path.join(absoluteOutDir, subPath)

  // Write index page
  writeFile(path.join(changeOutDir, 'index.md'), generateChangeIndexPage(change, outDir))

  // Copy artifact files
  for (const artifact of change.artifacts) {
    const srcFile = path.join(change.dir, `${artifact}.md`)
    const destFile = path.join(changeOutDir, `${artifact}.md`)
    copyFile(srcFile, destFile)
  }
}

/**
 * One-call VitePress config helper that wires up the full openspec integration.
 *
 * Calls `generateOpenSpecPages()` synchronously (required before VitePress scans
 * for routes), then merges the openspec Vite plugin, nav entry, and sidebar section
 * into the provided config object.
 *
 * Other Vite plugins go into `vite.plugins` as usual — `withOpenSpec` appends to
 * the array without replacing it:
 *
 * @example
 * ```typescript
 * // docs/.vitepress/config.ts
 * import { defineConfig } from 'vitepress'
 * import { withOpenSpec } from 'vitepress-plugin-openspec'
 *
 * export default defineConfig(
 *   withOpenSpec({
 *     vite: { plugins: [myOtherPlugin()] }, // other plugins are preserved
 *     themeConfig: { nav: [], sidebar: {} },
 *   })
 * )
 * ```
 *
 * @param config - Your VitePress `UserConfig` object (same as what `defineConfig` accepts).
 * @param options - OpenSpec options. All fields are optional; defaults match `generateOpenSpecPages`.
 */
export function withOpenSpec<T extends Record<string, unknown>>(
  config: T,
  options: WithOpenSpecOptions = {},
): T {
  const specDir = options.specDir ?? './openspec'
  const outDir = options.outDir ?? 'openspec'
  const srcDir = options.srcDir ?? process.cwd()

  generateOpenSpecPages({ specDir, outDir, srcDir })

  const result = { ...config } as Record<string, unknown>

  // --- Vite plugin ---
  const vite = (result.vite ?? {}) as Record<string, unknown>
  const existingPlugins = (vite.plugins as unknown[]) ?? []
  result.vite = { ...vite, plugins: [...existingPlugins, openspec({ specDir, outDir, srcDir })] }

  const themeConfig = (result.themeConfig ?? {}) as Record<string, unknown>

  // --- Nav ---
  if (options.nav !== false) {
    const navEntry = openspecNav(specDir, { outDir })
    const existingNav = (themeConfig.nav as unknown[]) ?? []
    themeConfig.nav = [navEntry, ...existingNav]
  }

  // --- Sidebar ---
  if (options.sidebar !== false && !Array.isArray(themeConfig.sidebar)) {
    const sidebarKey = `/${outDir}/`
    const existingSidebar = (themeConfig.sidebar ?? {}) as Record<string, unknown>
    if (!existingSidebar[sidebarKey]) {
      themeConfig.sidebar = {
        ...existingSidebar,
        [sidebarKey]: generateOpenSpecSidebar(specDir, { outDir }),
      }
    }
  }

  result.themeConfig = themeConfig

  return result as T
}

export default openspec
